version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Porta para comunicação AMQP
      - "15672:15672" # Porta para a interface de gerenciamento web
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: meu_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: exemplo123
    volumes:
      - mongodb_data:/data/db

  # reserva:
  #   build:
  #     context: ./reserva
  #     dockerfile: Dockerfile
  #   container_name: reserva-service
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./reserva:/app
  #   depends_on:
  #     - rabbitmq
  #     - mongodb
  #   restart: unless-stopped

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "5173:80"
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - rabbitmq
  #     - mongodb
  #   restart: unless-stopped

  # pagamento:
  #   build:
  #     context: ./pagamento
  #     dockerfile: Dockerfile
  #   container_name: pagamento-service
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./pagamento:/app
  #   depends_on:
  #     - rabbitmq
  #     - mongodb
  #   restart: unless-stopped

  # bilhete:
  #   build:
  #     context: ./bilhete
  #     dockerfile: Dockerfile
  #   container_name: bilhete-service
  #   ports:
  #     - "3002:3002"
  #   volumes:
  #     - ./bilhete:/app
  #   depends_on:
  #     - rabbitmq
  #     - mongodb
  #   restart: unless-stopped

  # marketing:
  #   build:
  #     context: ./marketing
  #     dockerfile: Dockerfile
  #   container_name: marketing-service
  #   ports:
  #     - "3004:3004"
  #   volumes:
  #     - ./marketing:/app
  #   depends_on:
  #     - rabbitmq
  #     - mongodb
  #   restart: unless-stopped

  # session:
  #   build:
  #     context: ./session
  #     dockerfile: Dockerfile
  #   container_name: session-service
  #   ports:
  #     - "3005:3005"
  #   volumes:
  #     - ./session:/app
  #   depends_on:
  #     - rabbitmq
  #     - mongodb
  #   restart: unless-stopped

volumes:
  mongodb_data:
